services:
  ros2:
    image: osrf/ros:humble-desktop
    container_name: scara_ros2
    volumes:
      - .:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    network_mode: host
    command: bash -c "source /opt/ros/humble/setup.bash && cd /workspace && bash"
    stdin_open: true
    tty: true
